### PR TITLE
Update README.md to use our dokku link

### PR DESCRIPTION
**Pull request by ameymwalimbe**
In this PR, I change the README to use our team's dokku link.

### CODE REVIEW

**Comment by ru1nw** [comment]
looks good

**Review by ru1nw — APPROVED** [review]
looks goood

**Review by zachmiller-ucsb — APPROVED** [review]
LGTM

**Review by ru1nw — APPROVED** [review]
still looks good

**Review by mike-k999 — APPROVED** [review]
LGTM

**Pull request merged**
