### PR TITLE
Sophia - add ride Request Index Page

### LINKED ISSUE #54: add Ride Index Page
add a RideRequestIndexPage to display the table and the current ride requests and have a Create Ride Request Button at the top

### PR DESCRIPTION
**Pull request by SophiaWeiler**
In this PR, I am adding a RideRequestIndexPage to display the table and the current ride requests and have a Create Ride Request Button at the top. It also has a [storybook](https://ucsb-cs156-s23.github.io/proj-gauchoride-s23-5pm-4/prs/52/storybook/?path=/story/pages-ride-riderequestindexpage--default) component, tests and some edits to the RideForm file that are reflected in the other PRs as well to get the tests to pass. This makes progress to #7. Here is a picture of what the page will look like:

Screen Shot 2023-06-06 at 12 48 54 PM

### CODE REVIEW

**Review by strongani — DISMISSED** [review]
LGTM! 
storybook: https://ucsb-cs156-s23.github.io/proj-gauchoride-s23-5pm-4/prs/52/storybook/?path=/story/pages-ride-riderequestindexpage--default

**Review by strongani — DISMISSED** [review]
LGTM!

**Review by ameymwalimbe — DISMISSED** [review]
LGTM, no commented out code and relevant use of Stryker disable/restore.

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
