### PR TITLE
Michael hompage text

### LINKED ISSUE #6: Replace Home Page Text
Replace the home page with something suitable. For example, text such as:

This app is being built by the students of CMPSC 156 at UCSB to assist an effort to provide
transportation for UCSB students with mobility issues to be better able to get to and from class.

### PR DESCRIPTION
**Pull request by mike-k999**
In this PR we update the homepage text to something a bit more descriptive during development; closes #6

### CODE REVIEW

**Review by zachmiller-ucsb — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
We try to avoid committing changes to package-lock.json unless absolutely necessary.

Please consider removing this from your PR.

**Review by pconrad — CHANGES_REQUESTED** [review]
Would like to see package-lock.json removed from the PR.

Other than that, looks good to me for 5 pts.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
